### ISSUE TITLE
How to implement FP16?

### ISSUE THREAD

**Issue by 408550969** [saikumarGadde/tensorrt-ssd-easy#11]
Thank you for sharing the code. I have a few questions:
1. How to implement FP16?
2. Why wait for several seconds when running the inference and display the following lines:
----  Might be an error below, Error ---- 
Came till here 
Whats happening here ? 
Is it here 1
Is it here 2
Is it here 2.1
Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
@saikumarGadde @JingliangGao

**Comment by JingliangGao** [comment]
Maybe it depends on your hardware . An  example can be given is that my nvidia TX2 support FP16 , but server can not .

**Comment by 408550969** [comment]
Thanks
