### ISSUE TITLE
大哥請問怎麼取得bounding box，我畫出來的結果都是錯的

### ISSUE THREAD

**Issue by wardtsai** [saikumarGadde/tensorrt-ssd-easy#3]
因為tensorrt ssd的detecion_out有兩個output

我目前是取第一個output

它flatten後的排序應該是batch index, class, confidence, x1, y1, x2, y2？

**Comment by JingliangGao** [comment]
请问，你们make是怎么通过的，我cmake通过了，但Make失败了。
出错原因：/usr/include/opencv2/core/mat.hpp   很多变量未命名

请问如何解决呢？

**Comment by gaddekumar** [comment]
@wardtsai Yes, its in that order which is same as the caffe implementation.

**Comment by 408550969** [comment]
@wardtsai 请问你有碰到预测结果不准确的问题吗？
